plugins {
    id 'java'
}

group = 'com.ohgiraffers'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/org.springframework/spring-core
    implementation("org.springframework:spring-core:6.2.11")

    // https://mvnrepository.com/artifact/org.springframework/spring-beans
    implementation("org.springframework:spring-beans:6.2.11")

    // https://mvnrepository.com/artifact/org.springframework/spring-context
    implementation("org.springframework:spring-context:6.2.11")

    // https://mvnrepository.com/artifact/org.springframework/spring-expression
    implementation("org.springframework:spring-expression:6.2.11")

    // https://mvnrepository.com/artifact/org.springframework/spring-aop
    implementation("org.springframework:spring-aop:6.2.11")

    // https://mvnrepository.com/artifact/org.springframework/spring-aspects
    implementation("org.springframework:spring-aspects:6.2.11")

    // https://mvnrepository.com/artifact/org.springframework/spring-instrument
    implementation("org.springframework:spring-instrument:6.2.11")



    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}